export const Almada = {
  "nobility": {
    "post": {
      prefix: { x: ["d'", "de ", "di ", "da ", "von ", "vom ", "zu ", "Al'"] },
      "x": ["Abundil", "Agum", "Amazetti", "Alcorta", "Faran", "Kasim", "Shirasgan", "Berg ä. H.", "Bleichenwang", "Braast", "Cavazaro", "Culming", "Artesa", "Ernathesa", "Eschgei­er", "Franfeld", "Harmamund", "Jurios", "Lacara", "Madja­ni", "Phexhilf-Rabenstein", "Ragathsquell", "Rastino", "Rebenthal", "Scheffelstein", "Streitzig ä. H.", "Taladur ä. H.", "Vanya", "Viryamun", "Zalfor"]},
  },
  "normal": {
    "post": {
      "x": ["Adelbuhler", "Assiref", "Ballurat", "Brannofend", "Brannthagen", "Blaemendal", "Bolongaro", "Castan­yeda", "Cavazaro", "Contador", "Cronbiegler", "Dallenstein", "Degenhardt", "Dschadirez", "Fetthennen", "Frostwein", "Fur­lani", "Galandi", "Küferhilf", "Lamperez", "Lautenschläger", "Maltichio", "Manzanares", "Mirador", "Monzon", "Mudejar", "Muwallar", "Ossentani", "Pichelstein", "Pitanza", "Pipote", "Ra­gather", "Ragaza", "Rüdwein", "Schlehwein", "Sensendengler", "Sfalia", "Sfandini", "Sfapano", "Sforigan", "Sgirra", "Tauben­tanz", "Tefoso", "Trapani", "Valdepenya", "Vascagni", "Zulha­midez", "Zurriaga"],
    },
    "pre": {
      "m": ["Almadeo", "Almanzo", "Almanzor", "Alonso", "Alrico", "Alricio", "Alrigo", "Alriego", "Amando", "Assavo", "Azulejo", "Balbiano", "Bardojoz", "Batholo", "Biscarat", "Bodar", "Boromeo", "Boronathan", "Borondino", "Cahusac", "Caldaio", "Caldaios", "Cambados", "Cazorlenyo", "Dani­lo", "Eglamo", "Eglamor", "Erresto", "Escalio", "Eslam", "Eslamo", "Espejo", "Farugo", "Federigo", "Gaftaro", "Gerio", "Gerion", "Girolamo", "Gonzalo", "Gualdo", "Gujadal", "Hazanyo", "Hernando", "Hesindio", "Hillero", "Inaro", "Ianaro", "Igeno", "Iglorio", "Ingrimo", "Ippolito", "Isonzo", "Jacopo", "Jose­lito", "Kazanyo", "Lanvolo", "Laurenzio", "Lerico", "Lessandero", "Lodovico", "Ludovigo", "Luciano", "Lucio", "Lumino", "Madrano", "Maquedar", "Marboriano", "Moritatio", "Nazir", "Obidos", "Or­donyo", "Pelayo", "Perinyo", "Peziano", "Punino", "Rafik", "Rafim", "Rahjian", "Rahjiano", "Raul", "Raulo", "Rondrigo", "Rustam", "Rustamo", "Salvestro", "Sansovino", "Selindiano", "Selindio", "Servando", "Talfan", "Tassi­lo", "Tennetto", "Tessano", "Tolak", "Tsayano", "Urrito", "Valdemo­ro", "Valpo", "Vencelao", "Viento", "Volapio", "Yaberto", "Yalach", "Yanturio", "Yelador", "Zahir", "Zayano", "Zelonso"],
      "w": ["Ahumeda", "Aldea", "Aldonaza", "Almadea", "Amaria", "Antara", "Azila", "Baraya", "Bellameria", "Boronya", "Caldaya", "Caldja", "Caneya", "Concabella", "Corvara", "Daroca", "Debona", "Doloresa", "Dunyaca", "Elea", "Emiglia", "Escalada", "Esfera", "Eshilya", "Eslamida", "Eslamidia", "Esribeda", "Farfanya", "Fha­dime", "Firella", "Ghazalita", "Gonzaga", "Gujadanya", "Ilmice", "Ilmicea", "Imeria", "Ismeralda", "Jazemina", "Luciana", "Madalena", "Ma­queda", "Mirandola", "Mirhaneba", "Morena", "Noiona", "Nova­ra", "Olenga", "Olivenaca", "Pasqua", "Peliria", "Rabena", "Rahjada", "Rahjania", "Rhajineza", "Richeza", "Rifada", "Rinaya", "Rondrala", "Rondralia", "Shahane", "Sefira", "Siguenza", "Simanca", "Solivai", "Solsona", "Travanca", "Tsaia", "Tsaya", "Ulzedona", "Unata", "Us­anza", "Unicornia", "Valposella", "Vanoza", "Vibora", "Viminyoza", "Vinyaza", "Yanis", "Yaquiria", "Yedra", "Yegua", "Yesabella", "Zafi­ra", "Zalamea", "Zarpa", "Zarpada", "Zaya", "Zefira", "Zorilla"]
    }
  }
}
