export const Weiden = {
  "nobility": {
    "post": {
      prefix: { x: ["von ", "zu "] },
      "x": ["Auenfels", "Blauenburg", "Bibergau", "Binsböckel", "Birselburg", "Blaubinge", "Dergelquell", "Fälklin", "Finsterbach", "Fuchshag", "Grauenfels", "Grîngelbaum", "Harlburg", "Hohenstein", "Leuenfeste", "Löwenhaupt", "Nordfalk", "Pandlaril", "Rotenwasser", "Rotwasser", "Schneehag", "Schnewlin", "Schrauffenfels", "Sichelbruch", "Weißenstein", "Weiden"]},
  },
  "normal": {
    "post": {
      "m": ["Ackermann", "Brachfelder", "Buthner", "Danckert", "Donnerbacher", "Erlenfold", "Fahrenholz", "Faulhaber", "Finsterbacher", "Flösser", "Freidank", "Ganzert", "Gerber", "Hohenwald", "Hollerheider", "Ibendorn", "Kolenbrander", "Morgenroth", "Mühlenfels", "Netzknüpfer", "Orkendräu", "Orkenhauer", "Rathilsteiner", "Riemenschneider", "Rindsherder", "Rohleder", "Runhager", "Schmiedemann", "Teichenberger", "Ulmenschläger", "Waldner"],
      "w": ["Ackerfrau", "Brachfelder", "Buthner", "Danckert", "Donnerbacherin", "Erlenfold", "Fahrenholz", "Faulhaberin", "Finsterbacherin", "Flösser", "Freidank", "Ganzert", "Gerberin", "Hohenwald", "Hollerheiderin", "Ibendorn", "Kolenbranderin", "Morgenroth", "Mühlenfels", "Netzknüpferin", "Orkendräu", "Orkenhauerin", "Rathilsteinerin", "Riemenschneiderin", "Rindsherdin", "Rohleder", "Runhager", "Schmiedefrau", "Teichenbergerin", "Ulmenschlägerin", "Waldnerin"],
    },
    "pre": {
      "m": ["Ailfir", "Ailgrimm", "Alarwin", "Aldewein", "Angilbert", "Angrist", "Anshag", "Arbolf", "Arlan", "Arnod", "Arnulf", "Avon", "Bärfried", "Baeromar", "Bernhelm", "Binsbart", "Borckhardt", "Bunsenhold", "Dankward", "Darwolf", "Derling", "Dietrad", "Dolgon", "Drachwill", "Dreufang", "Edil", "Efferdin", "Eichbart", "Emmeran", "Erlwulf", "Falber", "Feenwart", "Feenwardt", "Ferling", "Finglan", "Firl", "Firnmar", "Firutin", "Geldor", "Gerwulf", "Gille", "Giselhold", "Gorge", "Grimmfold", "Hargord", "Harmwulf", "Hartmann", "Hasrolf", "Heldar", "Herdan", "Ilmar", "Ilmbold", "Ingerman", "Ingram", "Ingramm", "Jargold", "Jarlan", "Josold", "Karfang", "Kerling", "Knorrhold", "Lanzelund", "Lein", "Leueman", "Lingmar", "Marbert", "Marmwulf", "Meinhardt", "Menzel", "Nassing", "Nolle", "Norsold", "Odilbert", "Olin", "Pagol", "Perdan", "Phexlieb", "Radumar", "Rodunk", "Rondril", "Rondreich", "Sadelhold", "Sighelm", "Siltja", "Tannfried", "Terkol", "Tiro", "Thimorn", "Thordenin", "Thorolf", "Tobor", "Uldreich", "Ulfert", "Waidhart", "Waldemar", "Weldmar", "Wilfing", "Wolfhelm", "Yann"],
      "w": ["Aartrude", "Adilgunde", "Ailgrid", "Alwen", "Alwenwid", "Amselgunde", "Ardariel", "Arline", "Bärlind", "Bärlinde", "Bärtraut", "Bormunde", "Danje", "Derlinde", "Dylga", "Elftraut", "Elftraute", "Elfwid", "Elfwidde", "Ellmholda", "Enn", "Erlgard", "Erlinde", "Fann", "Farlgard", "Farline", "Farnlieb", "Feengund", "Feengunde", "Fenia", "Feyenholde", "Firre", "Fiya", "Fredegunde", "Freugern", "Frohlinde", "Furgund", "Gernlind", "Gilamund", "Gun", "Gunelde", "Gusella", "Gwynna", "Helchtrut", "Helchtruta", "Hennya", "Herdlind", "Hilmtrud", "Hilmtrude", "Holdtraude", "Ilfwid", "Illa", "Ilme", "Irlgunde", "Kunn", "Kupunda", "Lann", "Lanzelind", "Linje", "Liebholde", "Luitperga", "Maidholde", "Matissa", "May", "Mirnhilde", "Nalle", "Neunhild", "Nifgunde", "Olginai", "Omwid", "Omwidda", "Praida", "Raugunde", "Rondperga", "Rondragabund", "Rechhilde", "Rinnfolde", "Sindaja", "Tannfriede", "Thargrîn", "Traute", "Ullgreîn", "Waidgunde", "Walbirg", "Walderia", "Waldtraute", "Waliburia", "Walpurga", "Yandebirg", "Yolina"]
    }
  }
}
