export const Nordmarken = {
  "nobility": {
    "post": {
      prefix: { x: ["von ", "zu "] },
      "x": ["Altenfurt", "Barschengrund", "Ebersdorf", "Eisenhuett", "Eisenstein", "Eisenwacht", "Eisenwald", "Elenvina", "Firnholz", "Föhrenschild", "Graufurt", "Greifax", "Halwartshof", "Hardenfels", "Herrenwalde", "Ibenburg", "Kaldenberg", "Kranick", "Liepenstein", "Meilingen", "Nablafurt", "Nablafurten", "Quakenbrück", "Rabenstein", "Riedenburg", "Schleiffenröchte", "Schlüsselburg", "Schnakensee", "Schönwald", "Schweinsfold", "Schwertleihe", "Steinfels", "Sturmfels ä. H.", "Tandosch", "Tannwirk", "Tiefenthal", "Tsafelde", "Twergengrund", "Vairningen", "Weiseprein", "Weissenberg", "Wolfsstein"]},
  },
  "normal": {
    "post": {
      "x": ["Andersin", "Armshaus", "Arrelfinger", "Bachenbrecht", "Bächerle", "Bertenschlag", "Bock", "Dernheim", "Dohlfelder", "Dreyschwerdt", "Eisner", "Engstrand", "Fatzmann", "Fegentritt", "Fischle", "Flusswieser", "Freienstetter", "Gaucher", "Gliependiek", "Griff", "Haberle", "Häsler", "Hintersass", "Hugendubel", "Isenbruckner", "Kammergrad", "Lausinger", "Leerscheun", "Kätner", "Katorz", "Kessler", "Klingenbruch", "Klippstein", "Knurrpfütz", "Kupferfeld", "Malter", "Muckenschlag", "Rädle", "Runkler", "Salmfang", "Sebelgarn", "Simis", "Spilman", "Tobelberg", "Trappdorf", "Uhl", "Wolfshag", "Zehntner", "Zweyfeldt"],
    },
    "pre": {
      "m": ["Aarwin", "Abbo", "Adalhard", "Adalric", "Adelhelm", "Aedin", "Aidan", "Aldebaran", "Amaldus", "Amiel", "Angroban", "Angrond", "Arsan", "Aureus", "Baldos", "Barnabas", "Basin", "Bellermin", "Bernhelm", "Bobar", "Boromar", "Boronslob", "Brun", "Celio", "Cian", "Dankrath", "Donewald", "Dorcas", "Ebruiel", "Eddo", "Efferdfrid", "Elko", "Eremalrik", "Ernbrecht", "Firunhard", "Fulger", "Garmwart", "Gebbert", "Gerfrid", "Godehard", "Gorwin", "Grifo", "Hagrian", "Hagunald", "Hartuwal", "Hechard", "Helmbrecht", "Heridan", "Hesindagoras", "Hilberian", "Hlûthar", "Hlûthard", "Hraban", "Hrabanus", "Humban", "Ingeras", "Ingmar", "Ingrawin", "Irian", "Jast", "Jorgast", "Kalver", "Koradin", "Leodegar", "Leuenhard", "Lucrann", "Madard", "Maedard", "Manegold", "Marborad", "Markward", "Meinwerk", "Merkan", "Morand", "Nerek", "Odumir", "Ossian", "Pagol", "Phewin", "Praiobold", "Praiogrim", "Praiopha", "Praiophan", "Praiophatius", "Praiophanatius", "Praiostan", "Praiowulf", "Quendan", "Rabanus", "Radbod", "Radulf", "Reginbald", "Rondragoras", "Rupo", "Sandrad", "Sigred", "Sirin", "Traviard", "Tsamar", "Ucuriard", "Ulfried", "Vitold", "Walram", "Wandregisil", "Wando", "Welferich", "Winfrid", "Wunnemar", "Yendan"],
      "w": ["Adelgund", "Adelgunde", "Adula", "Alueh", "Amadis", "Auxilia", "Basilissa", "Beregis", "Bilhild", "Boromada", "Calderine", "Daria", "Dhuoda", "Drahomira", "Durinja", "Eilada", "Elwene", "Ermelind", "Fastrada", "Frederun", "Gelda", "Gezelin", "Gratfride", "Gratfriede", "Grimmhel", "Guda", "Gundelin", "Hadelin", "Harlindis", "Helmtrud", "Hemma", "Ermenegild", "Ermenegilda", "Hermenegild", "Hermenegilda", "Hesindigund", "Idra", "Imelda", "Isavena", "Isweine", "Isweine", "Isewein", "Iswen", "Isfrid", "Isora", "Ituberga", "Itta", "Ivetta", "Jocasta", "Jolenta", "Lindwin", "Lioba", "Liudbirg", "Liudtbirg", "Luassa", "Lucasta", "Luzia", "Madalberta", "Madalin", "Mafalda", "Marbolena", "Maura", "Mengard", "Meingard", "Meingarde", "Mika", "Miril", "Noitburg", "Oda", "Odelinde", "Odewinse", "Odrud", "Omelda", "Perainhuld", "Perainhulda", "Perihel", "Pheguda", "Phegunda", "Phexline", "Praialda", "Prainabirg", "Praioberga", "Praiobierga", "Praitrud", "Prianna", "Rabanna", "Radegund", "Raxa", "Regintrud", "Richild", "Roana", "Rondralda", "Rotrud", "Rotrude", "Sabea", "Salaberga", "Salabierga", "Siric", "Talina", "Travialin", "Tsaala", "Tsaalda", "Tsasalda", "Tsasala", "Utsinde", "Vea", "Veriya", "Wiltrud", "Wina", "Winifred", "Witta", "Wolfrida", "Wulfrun", "Zaberga", "Zaraffa"]
    }
  }
}
